### ISSUE TITLE
10_2_X branch?

### ISSUE THREAD

**Issue by jmduarte** [cms-btv-pog/RecoBTag-PerformanceMeasurements#108]
Hi @mverzett ,

Will there be a 10_2_X branch of the BTagAnalyzer? We would like to have one for running DeepAK8, DeepDoubleB/C

Thanks!

@ferencek @alefisico

**Comment by mverzett** [comment]
There should definitely be one. @rauser can you create one out of the latest 10.1? We will need it for the 2018 SF campaign anyhow.

**Comment by rauser** [comment]
Yes, I'll take care of it

**Comment by rauser** [comment]
The 10_2_X branch is ready (https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/tree/10_2_X). I ran the tests successfully, but please tell me if you experience any problems. Cheers, Johann
