### ISSUE TITLE
Setting the deepflavour discriminator to -10 always

### ISSUE THREAD

**Issue by emilbols** [cms-btv-pog/RecoBTag-PerformanceMeasurements#109]
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/10_1_X/plugins/BTagAnalyzer.cc#L2753-L2755

it should be DeepFlavourB > -5

it is also done incorrectly for the negative tagger.

**Comment by rauser** [comment]
Fixed. Thanks for spotting this!
