### ISSUE TITLE
"Invalid Jet Inputs" for Run3 runBTagAnalyzer_cfg.py

### ISSUE THREAD

**Issue by daniel-sunyou-li** [cms-btv-pog/RecoBTag-PerformanceMeasurements#146]
Hello, 

I've been trying out runBTagAnalyzer_cfg.py on the 12_2_X branch for Winter22 Run3 MC samples to do some Run3 studies. I'm using the CMSSW release 12_2_3_patch1, as it is the release the samples were produced on. I'm encountering an issue when running `cmsRun runBTagAnalyzer_cfg.py runOnData=False defaults=Run3 runEventInfo=True` where the module FastjetJetProducer gives me the message: "Did not specify appropriate inputs for VirtualJetProducer, Abort!" 

I saw that a [similar issue](https://github.com/cms-sw/cmssw/issues/36322) was addressed initially suspecting the CMSSW release being the issue, but that was closed. Looking at the most recent commit date and when that issue was opened, I don't suspect that the solution was propagated yet to the 12_2_X branch. I am wondering if it has been resolved privately by someone in the BTV group or if there's any additional insight into what the problem is.

From my own investigating, I suspected that it would have to come from [this line](https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/test/runBTagAnalyzer_cfg.py#L963) in the EDAnalyzer config file and be related to the `src` argument as that is [where the error message comes from](https://github.com/cms-sw/cmssw/blob/CMSSW_12_2_X/RecoJets/JetProducers/plugins/VirtualJetProducer.cc#L333-L390). I had tested out a few other options for the `src` argument as indicated [here](https://github.com/cms-sw/cmssw/blob/CMSSW_12_2_X/RecoJets/JetProducers/python/ak4PFJets_cfi.py), but did not have any success.

**Comment by soureek** [comment]
@daniel-sunyou-li We have moved to NanoAOD-based setup for Run3. See [here](https://github.com/cms-btv-pog/BTVNanoCommissioning). Please check out this new repository.
The MiniAOD-based BTagAnalyzer setup is not supported anymore.
