### ISSUE TITLE
including ttbar variables in the tree

### ISSUE THREAD

**Issue by fojensen** [cms-btv-pog/RecoBTag-PerformanceMeasurements#71]
I would like to set the useTTBarFilter to true [1] so that I can get all the relevant ttbar variables into the trees. I don't want to filter any of the events out, so in the ttbarselectionfilter module I set selectAll to true [2] but this then causes a seg fault, I attached the log file [3] to this post.
Am I doing something funny?

[1]
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/test/runBTagAnalyzer_cfg.py#L108-L112

[2]
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/python/TTbarSelectionFilter_cfi.py#L6

[3]
[log.txt](https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/files/1733266/log.txt)

**Comment by mverzett** [comment]
@fojensen , I can reproduce your error. I will have a look at it later in the afternoon.

**Comment by mverzett** [comment]
@fojensen I should have fixed the problem by adding a protection that, in case of failing the filter, the MET values are set to -10. Please check that these unphysical values do not enter in your analysis.
Please let me also know if everything works fine and if you plan to keep using this workflow.

**Comment by fojensen** [comment]
yes - that seems to have fixed it - thank you
I am going to keep using this workflow for a little while, to understand the mc before applying any cuts.
