### ISSUE TITLE
muon id

### ISSUE THREAD

**Issue by fojensen** [cms-btv-pog/RecoBTag-PerformanceMeasurements#72]
I am interested in adding muons from the slimmedMuons collection into the ntuples, so I set storePatMuons to true[1]; and that works fine. 
I think there is an issue with the particular method called to fill some of the variables required for muon identification[2]. Below, there are three lines a, b, c where I first state what the function should be as stated on the muonpog twiki, and then the link to the line in the current BTagAnalyzer.cc code.

a) I believe we should be using: it->globalTrack()->hitPattern().numberOfValidMuonHits();
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/plugins/BTagAnalyzer.cc#L1500

b) I believe we should be using: it->numberOfMatchedStations()
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/plugins/BTagAnalyzer.cc#L1501

c) I believe we should be using: it->innerTrack()->hitPattern().trackerLayersWithMeasurement() 
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/plugins/BTagAnalyzer.cc#L1497

[1]
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/python/bTagAnalyzerCommon_cff.py#L15

[2]
https://twiki.cern.ch/twiki/bin/viewauth/CMS/SWGuideMuonIdRun2#Tight_Muon
(then click "Show table")

**Comment by mverzett** [comment]
@fojensen it is difficult to disagree :), the table clearly states that we are doing it wrong. Can you prepare a pull request? Also, you could be directly calling isTight/Medium/Soft etc.. and store it in boolean branches and drop the rest saving some space. @ferencek @imarches what do you think about it?

**Comment by ghost** [comment]
Dear all,

I agree, if objects need to be updated a PR would be great. In case of doubts on some quantities, please, let us know, we can contact a Muon expert. Thanks a lot!

**Comment by fojensen** [comment]
I made a PR to update the three functions:
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/pull/73

**Comment by fojensen** [comment]
I do agree that switching to the isLooseMuon(), isMediumMuon(), isTightMuon() functions for the muon id is nicer than each cut independently (given no one needs the individual variables?). At the time I wanted to make a quick fix for the id variables.

Is anyone aware of a similar id 'shortcut' variable for the pat::Jet class?
https://twiki.cern.ch/twiki/bin/view/CMS/JetID13TeVRun2017

**Comment by mverzett** [comment]
Long time ago it was embedded in miniAODs userFloats, but given we should be able to run on non miniAOD as well I would not be in favour of such change

**Comment by fojensen** [comment]
I made a PR to update the muon id to make direct calls to isMediumMuon (for example).
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/pull/74
