### ISSUE TITLE
update to global tags in runBTagAnalyzer_cfg.py?

### ISSUE THREAD

**Issue by fojensen** [cms-btv-pog/RecoBTag-PerformanceMeasurements#75]
For a release in 94X, running on data from Run2017*-17Nov2017-v1 and mc from 
RunIIFall17MiniAOD-94X_mc2017_realistic_v10-v*, I believe the current default globaltags in runBTagAnalyzer_cfg.py:
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/test/runBTagAnalyzer_cfg.py#L53-L62

should be changed to more current ones:
https://twiki.cern.ch/CMS/PdmV2017Analysis#Conditions
i.e.
data:  94X_dataRun2_ReReco_EOY17_v2
mc: 94X_mc2017_realistic_v10

**Comment by kskovpen** [comment]
This is automatically setup from https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/python/defaults/Moriond18.py when specifying defaults=Moriond18 in the run options.

**Comment by fojensen** [comment]
ok
great
thank you!
