### ISSUE TITLE
adding triggers to BTagAnalyzer ntuples?

### ISSUE THREAD

**Issue by fojensen** [cms-btv-pog/RecoBTag-PerformanceMeasurements#78]
I would like to add some triggers to the ntuples. I believe I would add them to this list:
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/python/bTagAnalyzerCommon_cff.py#L62-L108

What I don't understand is how the size of EventInfo.BitTrigger is set:
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/plugins/BTagAnalyzer.cc#L1584
It gets set to size of 1 for all lists of triggers with 31 elements or less? Am I reading something wrong? Should the size not just be set to triggerPathNames_.size()?

Thank you,
~Frank

**Comment by carolinecollard** [comment]
Hi Frank,

you can have a look at 
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/test/BTagAnalyzerMacros/CommPlotProducer.C#L1927:L2073

to see how the trigger information is decoded.
Unfortunately this file does not seem to be up-to-date on git
(in https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/test/BTagAnalyzerMacros/CommPlotProducer.C#L2022 
30 should be replaced by 32 and similarly for the other remaining triggers), 

but it should be helpful to understand the logic: the order of the list in 
> https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/python/bTagAnalyzerCommon_cff.py#L62-L108 <https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/python/bTagAnalyzerCommon_cff.py#L62-L108>
is very important. So put your new trigger at the bottom of the list and count its ranking (starting at 0), it should appear in position 40 (if I am correct).

TODO from my side (one day ;-) ): commit a new version of CommPlotProducer.C with the correct decoding of the trigger info. The qcd-commissioning team has the correct decoding, so there is no worry on our side, it is just better to have git up-to-date...

Cheers,
Caroline

**Comment by ghost** [comment]
Just to add that if this trigger is for the ttbar channel, as I supposed, it should better be added to the specific list of ttbar triggers, no to this list of commissioning triggers for QCD.

**Comment by ghost** [comment]
So around here:

https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/python/TTbarSelectionProducer_cfi.py#L13

**Comment by fojensen** [comment]
Is it correct to say that this portion of the configuration is not used anywhere else in the code?:
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/293b9b18ca55985785109fb08fffeeb996ab81cd/python/bTagAnalyzerCommon_cff.py#L109-L116

**Comment by fojensen** [comment]
I made a PR to add the HLT_Mu50_v trigger to the ttbar list:
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/pull/81

As a side note, I also think these two lines of code can be dropped as they do not currently do anything:
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/plugins/TTbarSelectionProducer.cc#L150
https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/9_4_X/plugins/TTbarSelectionProducer.cc#L162

**Comment by ghost** [comment]
Hi @fojensen 

yes, these lines 

https://github.com/cms-btv-pog/RecoBTag-PerformanceMeasurements/blob/293b9b18ca55985785109fb08fffeeb996ab81cd/python/bTagAnalyzerCommon_cff.py#L109-L116

should be currently unused and removable.

Ivan

**Comment by fojensen** [comment]
I (finally) got the trigger in; thanks for the help.
